# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  iEDA = {
    pname = "iEDA";
    version = "59662dcd768165f3957003522cb929d42b252023";
    src = fetchgit {
      url = "https://gitee.com/oscc-project/iEDA.git";
      rev = "59662dcd768165f3957003522cb929d42b252023";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LaFGp9U7K+HmvHW1XK6HyUB/WM5O3y/tngul+cdbCP4=";
    };
    date = "2025-12-23";
  };
}
