# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  iEDA = {
    pname = "iEDA";
    version = "699a03ec6b74f3e0711ad9c247431f7239729f95";
    src = fetchgit {
      url = "https://gitee.com/oscc-project/iEDA.git";
      rev = "699a03ec6b74f3e0711ad9c247431f7239729f95";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-I5NqzqrXMv95cZFLdILMrht7JxbmnE0ZqQ0WFnhSfeU=";
    };
    date = "2025-10-27";
  };
}
