# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  iEDA = {
    pname = "iEDA";
    version = "fd2edab9b8ab29b4848d727a5f8606623da879f1";
    src = fetchgit {
      url = "https://gitee.com/oscc-project/iEDA.git";
      rev = "fd2edab9b8ab29b4848d727a5f8606623da879f1";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tz5dzVU3nYgmhRtqONwE513DCwoUP3v2wNVjSgVUtJQ=";
    };
    date = "2025-09-01";
  };
}
